stages:
  - build
  - deploy

.build_job: &build_job
  image:
    name: alpine/helm:3.14.1
    entrypoint: [""]
  script:
    - helm dependency update charts/${CHART}
    - helm package charts/${CHART}
  artifacts:
    expire_in: 1 week
    paths:
      - ${CHART}*.tgz
  rules:
    - changes:
      - charts/${CHART}/*

.deploy_gitlab_job: &deploy_gitlab_job
  image:
    name: alpine/helm:3.14.1
    entrypoint: [""]
  before_script:
    - apk add git
    - helm plugin install https://github.com/chartmuseum/helm-push --version=v0.10.4
    - helm repo add gitlab-repo --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/stable
  script:
    - helm cm-push --force ${CHART}*.tgz gitlab-repo
  rules:
    - when: manual
      allow_failure: true
      changes:
      - charts/${CHART}/*

.deploy_s3_job: &deploy_s3_job
  image:
    name: alpine/helm:3.14.1
    entrypoint: [""]
  before_script:
    - apk add git
    - helm plugin install https://github.com/hypnoglow/helm-s3.git --version 0.16.0
    - helm repo add s3-repo ${S3_BUCKET}
  script:
    - helm s3 push --relative --force ${CHART}*.tgz s3-repo
  rules:
    - when: manual
      allow_failure: true
      changes:
      - charts/${CHART}/*

helm-build-speedtest:
  needs: []
  stage: build
  variables:
    CHART: prometheus-speedtest-exporter
  <<: *build_job

helm-deploy-speedtest-gitlab:
  stage: deploy
  needs: ["helm-build-speedtest"]
  dependencies:
    - helm-build-speedtest
  variables:
    CHART: prometheus-speedtest-exporter
    CHART_TAG_PATTERN: /^${CHART}-v\d+.\d+.\d+/
  <<: *deploy_gitlab_job
  
helm-deploy-speedtest-s3:
  stage: deploy
  needs: ["helm-build-speedtest"]
  dependencies:
    - helm-build-speedtest
  variables:
    CHART: prometheus-speedtest-exporter
    CHART_TAG_PATTERN: /^${CHART}-v\d+.\d+.\d+/
  <<: *deploy_s3_job
